from enum import StrEnum


class Verdict(StrEnum):
    CORRECT = "CORRECT"
    FIXABLE = "FIXABLE"
    WRONG = "WRONG"


class StepType(StrEnum):
    GENESIS = "GENESIS"
    PRE_GENERATOR = "PRE_GENERATOR"
    POST_GENERATOR = "POST_GENERATOR"
    PRE_VERIFIER = "PRE_VERIFIER"
    POST_VERIFIER = "POST_VERIFIER"
    PRE_REVISER = "PRE_REVISER"
    POST_REVISER = "POST_REVISER"
    TOOL_CALL = "TOOL_CALL"
    HUMAN_GATE = "HUMAN_GATE"
    MANIFEST = "MANIFEST"


class RunStatus(StrEnum):
    INITIALIZING = "INITIALIZING"
    GENERATING = "GENERATING"
    VERIFYING = "VERIFYING"
    REVISING = "REVISING"
    AWAITING_HUMAN = "AWAITING_HUMAN"
    FINALIZING = "FINALIZING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    NO_OUTPUT = "NO_OUTPUT"


class CitationCheckResult(StrEnum):
    VERIFIED = "VERIFIED"
    METADATA_MISMATCH = "METADATA_MISMATCH"
    NOT_FOUND = "NOT_FOUND"
    CLAIM_UNSUPPORTED = "CLAIM_UNSUPPORTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class ConfidenceTier(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    VERY_LOW = "VERY_LOW"


class CheckpointBackend(StrEnum):
    SQLITE = "SQLITE"
    POSTGRES = "POSTGRES"
