# src/slop_research_factory/types/hai_card.py

"""
HAI (Human–AI Interaction) Card types — D-2 §10.

Four frozen dataclasses compose bottom-up into the
top-level :class:`HaiCard`:

  :class:`ModelUsageRecord`
      Per-model, per-node token/call accounting.

  :class:`ProcessSummary`
      Cycle, rejection, and revision counts.

  :class:`VerificationSummary`
      Final verification outcome (verdict, confidence,
      tier, deterministic/citation tallies).

  :class:`HaiCard`
      Complete card ready for rendering (Step 11).

Key invariants enforced at construction:

- ``human_review_status`` defaults to ``UNREVIEWED``.

  ``REVIEWED`` requires both ``human_reviewer`` and
  ``human_review_timestamp`` (D-7 §7.4).
- ``security_guarantee`` must be byte-identical to the

  :data:`SECURITY_GUARANTEE` constant (D-1 §9).
- ``disclaimer`` must be non-empty.
- All SHA-256 hashes: 64-char lowercase hexadecimal.
- All timestamps: timezone-aware (UTC expected).

Spec references:
    D-1 §9    Security guarantee (byte-identical text).
    D-2 §10   HAI Card schema.
    D-6 §6    Renderer contract.
    D-7 §7.4  Human review governance.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from slop_research_factory.types.enums import (
    HumanReviewStatus,
    NodeName,
    Verdict,
)
from slop_research_factory.types.hashing import SHA256_LOWERCASE_RE

__all__ = [
    "DEFAULT_DISCLAIMER",
    "HaiCard",
    "ModelUsageRecord",
    "ProcessSummary",
    "SECURITY_GUARANTEE",
    "VerificationSummary",
]

# ── Constants ────────────────────────────────────────────

SECURITY_GUARANTEE: str = (
    "This document was generated by an AI system and has "
    "not been independently verified by a qualified human "
    "domain expert. The cryptographic provenance chain "
    "provides a tamper-evident record of the generation "
    "process but does not guarantee the accuracy, "
    "completeness, or fitness for purpose of the content. "
    "Users must perform their own due diligence before "
    "relying on any claims, data, or recommendations "
    "contained herein."
)
"""Canonical security guarantee — D-1 §9.

Must appear byte-identical in every rendered HAI Card.
"""

DEFAULT_DISCLAIMER: str = (
    "AI-Generated Research Output \u2014 This document was "
    "produced by the SLOP Research Factory, an automated "
    "research generation pipeline. All content requires "
    "independent human review before use in any "
    "decision-making context."
)
"""Convenience default for the ``disclaimer`` field.

Callers may supply a different non-empty string.
"""


# ── ModelUsageRecord ─────────────────────────────────────


@dataclass(frozen=True)
class ModelUsageRecord:
    """Per-model, per-node token and call accounting.

    Attributes:
        model_id:      LLM model identifier
                       (e.g. ``"claude-sonnet-4-20250514"``).
        node_name:     Pipeline node that used this model.
        input_tokens:  Total input tokens across all calls.
        output_tokens: Total output tokens across all calls.
        call_count:    Number of LLM invocations.
    """

    model_id: str
    node_name: NodeName
    input_tokens: int
    output_tokens: int
    call_count: int

    def __post_init__(self) -> None:
        if not self.model_id:
            raise ValueError("model_id must be non-empty")
        if self.input_tokens < 0:
            raise ValueError(f"input_tokens must be >= 0, got {self.input_tokens}")
        if self.output_tokens < 0:
            raise ValueError(f"output_tokens must be >= 0, got {self.output_tokens}")
        if self.call_count < 0:
            raise ValueError(f"call_count must be >= 0, got {self.call_count}")


# ── ProcessSummary ───────────────────────────────────────


@dataclass(frozen=True)
class ProcessSummary:
    """Cycle, rejection, and revision counts.

    Attributes:
        total_cycles:    Total Generate → Verify (→ Revise)
                         cycles executed.
        rejection_count: WRONG verdicts (full rewrites).
        revision_count:  FIXABLE verdicts (targeted repairs).
    """

    total_cycles: int
    rejection_count: int
    revision_count: int

    def __post_init__(self) -> None:
        if self.total_cycles < 0:
            raise ValueError(f"total_cycles must be >= 0, got {self.total_cycles}")
        if self.rejection_count < 0:
            raise ValueError(f"rejection_count must be >= 0, got {self.rejection_count}")
        if self.revision_count < 0:
            raise ValueError(f"revision_count must be >= 0, got {self.revision_count}")


# ── VerificationSummary ─────────────────────────────────


@dataclass(frozen=True)
class VerificationSummary:
    """Final verification outcome.

    ``tier_reached`` follows D-4 §3::

        1  T1 — deterministic checks only
        2  T2 — T1 + LLM verification
        3  T3 — T2 + citation verification

    Attributes:
        final_verdict:        CORRECT, FIXABLE, or WRONG.
        verdict_confidence:   Composed confidence [0.0, 1.0].
        tier_reached:         Highest verification tier
                              completed (1–3).
        deterministic_passed: T1 checks that passed.
        deterministic_total:  T1 checks executed.
        citations_verified:   Citations confirmed by tool
                              lookup.
        citations_total:      Total citations extracted.
    """

    final_verdict: Verdict
    verdict_confidence: float
    tier_reached: int
    deterministic_passed: int
    deterministic_total: int
    citations_verified: int
    citations_total: int

    def __post_init__(self) -> None:
        if not (1 <= self.tier_reached <= 3):
            raise ValueError(f"tier_reached must be 1–3, got {self.tier_reached}")
        if not (0.0 <= self.verdict_confidence <= 1.0):
            raise ValueError(f"verdict_confidence must be 0.0–1.0, got {self.verdict_confidence}")
        if self.deterministic_passed < 0:
            raise ValueError(f"deterministic_passed must be >= 0, got {self.deterministic_passed}")
        if self.deterministic_total < 0:
            raise ValueError(f"deterministic_total must be >= 0, got {self.deterministic_total}")
        if self.deterministic_passed > self.deterministic_total:
            raise ValueError(
                f"deterministic_passed "
                f"({self.deterministic_passed}) "
                f"> deterministic_total "
                f"({self.deterministic_total})"
            )
        if self.citations_verified < 0:
            raise ValueError(f"citations_verified must be >= 0, got {self.citations_verified}")
        if self.citations_total < 0:
            raise ValueError(f"citations_total must be >= 0, got {self.citations_total}")
        if self.citations_verified > self.citations_total:
            raise ValueError(
                f"citations_verified "
                f"({self.citations_verified}) "
                f"> citations_total "
                f"({self.citations_total})"
            )


# ── HaiCard (D-2 §10) ───────────────────────────────────


@dataclass(frozen=True)
class HaiCard:
    """Complete Human–AI Interaction Card.

    This is the **type layer** only.  Rendering to Markdown
    is handled by ``output/hai_card_renderer.py`` (Step 11).

    Fields are ordered required-first, defaulted-last to
    satisfy ``dataclass`` field ordering rules.

    Attributes:
        run_id:                   Unique run identifier.
        generated_at:             UTC timestamp of card
                                  generation (tz-aware).
        brief_title:              Human-readable brief title.
        brief_hash:               SHA-256 of the brief JSON.
        models_used:              Per-model usage records.
        process:                  Cycle/revision/rejection
                                  summary.
        verification:             Verification outcome.
        total_seals:              Seal count in provenance
                                  chain.
        chain_integrity_verified: Whether chain hash linkage
                                  passed verification.
        final_seal_hash:          SHA-256 of the last seal.
        output_hash:              SHA-256 of ``paper.md``.
        disclaimer:               Non-empty disclaimer text.
        total_input_tokens:       Aggregate input tokens.
        total_output_tokens:      Aggregate output tokens.
        total_estimated_cost_usd: Aggregate estimated cost.
        output_license:           Output content license
                                  (e.g. ``"CC BY 4.0"``).
        code_license:             Source code license
                                  (e.g. ``"Apache-2.0"``).
        human_review_status:      Review state; defaults to
                                  ``UNREVIEWED``.
        human_reviewer:           Reviewer identity (required
                                  when ``REVIEWED``).
        human_review_timestamp:   Review timestamp (required
                                  when ``REVIEWED``).
        human_review_notes:       Free-text review notes.
        security_guarantee:       Must be byte-identical to
                                  :data:`SECURITY_GUARANTEE`.
    """

    # ── Required fields ──────────────────────────────────

    # Identity
    run_id: str
    generated_at: datetime
    brief_title: str
    brief_hash: str

    # Models
    models_used: tuple[ModelUsageRecord, ...]

    # Process
    process: ProcessSummary

    # Verification
    verification: VerificationSummary

    # Provenance
    total_seals: int
    chain_integrity_verified: bool
    final_seal_hash: str

    # Output
    output_hash: str

    # Governance text
    disclaimer: str

    # Cost
    total_input_tokens: int
    total_output_tokens: int
    total_estimated_cost_usd: float

    # Attribution
    output_license: str
    code_license: str

    # ── Defaulted fields ─────────────────────────────────

    human_review_status: HumanReviewStatus = HumanReviewStatus.UNREVIEWED
    human_reviewer: str | None = None
    human_review_timestamp: datetime | None = None
    human_review_notes: str = ""
    security_guarantee: str = SECURITY_GUARANTEE

    # ── Validation ───────────────────────────────────────

    def __post_init__(self) -> None:
        _validate_hai_identity_and_hashes(self)
        _validate_hai_timestamps(self)
        _validate_hai_human_review(self)
        _validate_hai_governance_and_numbers(self)


def _validate_hai_identity_and_hashes(card: HaiCard) -> None:
    if not card.run_id:
        raise ValueError("run_id must be non-empty")
    if not card.brief_title.strip():
        raise ValueError("brief_title must be non-empty")
    for name in (
        "brief_hash",
        "final_seal_hash",
        "output_hash",
    ):
        value = getattr(card, name)
        if not SHA256_LOWERCASE_RE.match(value):
            raise ValueError(f"{name} must be 64-char lowercase hex, got {value!r}")


def _validate_hai_timestamps(card: HaiCard) -> None:
    if card.generated_at.tzinfo is None:
        raise ValueError("generated_at must be timezone-aware (UTC)")
    if card.human_review_timestamp is not None and card.human_review_timestamp.tzinfo is None:
        raise ValueError("human_review_timestamp must be timezone-aware (UTC)")


def _validate_hai_human_review(card: HaiCard) -> None:
    if card.human_review_status is HumanReviewStatus.REVIEWED:
        if card.human_reviewer is None:
            raise ValueError("REVIEWED status requires human_reviewer")
        if card.human_review_timestamp is None:
            raise ValueError("REVIEWED status requires human_review_timestamp")


def _validate_hai_governance_and_numbers(card: HaiCard) -> None:
    if not card.disclaimer.strip():
        raise ValueError("disclaimer must be non-empty")
    if card.security_guarantee != SECURITY_GUARANTEE:
        raise ValueError("security_guarantee must be byte-identical to SECURITY_GUARANTEE constant")
    if card.total_seals < 0:
        raise ValueError(f"total_seals must be >= 0, got {card.total_seals}")
    if card.total_input_tokens < 0:
        raise ValueError(f"total_input_tokens must be >= 0, got {card.total_input_tokens}")
    if card.total_output_tokens < 0:
        raise ValueError(f"total_output_tokens must be >= 0, got {card.total_output_tokens}")
    if card.total_estimated_cost_usd < 0.0:
        raise ValueError(
            f"total_estimated_cost_usd must be >= 0, got {card.total_estimated_cost_usd}"
        )
    if not card.output_license.strip():
        raise ValueError("output_license must be non-empty")
    if not card.code_license.strip():
        raise ValueError("code_license must be non-empty")
